#!/bin/bash

set -Eeuo pipefail

system=$(lsb_release -si)

declare -A asdf_plugins
asdf_plugins[erlang]="26.0.2"
asdf_plugins[elixir]="1.15.7-otp-26"
asdf_plugins[golang]="1.20.4"
asdf_plugins[nodejs]="20.4.0"
asdf_plugins[pnpm]="7.32.5"
asdf_plugins[ruby]="3.2.2"

declare -a cargo_install=(ripgrep fd-find exa bat hexyl zoxide difftastic)

case ${system} in
  ManjaroLinux)
    echo "Running Manjaro setup..."

    # Enable pamac aur
    sudo sed -Ei '/EnableAUR/s/^#//' /etc/pamac.conf

    # Basics
    sudo pacman -S --noconfirm --needed base-devel ncurses libssh unixodbc libxslt fop

    # Install system packages
    declare -a packages=(direnv helix-git cider fish wezterm kwin-bismuth yin-yang mosh unzip ttf-sourcecodepro-nerd ttf-apple-emoji pre-commit watchexec)
    pamac install --no-upgrade --no-confirm ${packages}

    declare -a package_deps=(wezterm-terminfo wezterm-shell-integration plasma-wayland-session)
    pamac install --as-deps --no-upgrade --no-confirm ${package_deps}

    # Install asdf
    if [ ! -d "$HOME/.asdf" ]; then
      git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1
    fi
    . "$HOME/.asdf/asdf.sh"

    # Install asdf plugins
    for plugin in "${!asdf_plugins[@]}"; do
      asdf plugin add $plugin
      asdf install $plugin ${asdf_plugins[$plugin]}
    done

    # Install rust
    if [ ! -f "$HOME/.cargo/bin/cargo" ]; then
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    fi
    source "$HOME/.cargo/env"

    # Install some rust tools
    for tool in "${cargo_install[@]}"; do
      cargo install $tool
    done

    # Fisher package manager
    fish -c 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher'
    yadm restore -- ~/.config/fish/fish_plugins
    fish -c 'fisher update'

    # Enable librewolf native messenger
    ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
    sudo ln -s /usr/lib/mozilla/native-messaging-hosts /usr/lib/librewolf/native-messaging-hosts
    sudo mkdir -p /etc/1password
    echo -e "librewolf\nlibrewolf-bin" | sudo tee -a /etc/1password/custom_allowed_browsers

    ;;
  \?)
    echo "No bootstrap procedure for ${system}" >&2
    exit 1
    ;;
esac
