# Preferences
# ───────────

colorscheme gruvbox

hook global WinCreate ^[^*]+$ %{ add-highlighter window/ number-lines -hlcursor }

set global autoinfo command|onkey|normal
set global grepcmd 'rg -Hn'
set global indentwidth 2
set global scrolloff 3,3
set global tabstop 8
set global ui_options ncurses_assistant=clippy ncurses_wheel_down_button=0

# Highlight the word under the cursor
# ───────────────────────────────────

declare-option -hidden regex curword
set-face global CurWord default,rgb:4a4a4a

hook global NormalIdle .* %{
    eval -draft %{ try %{
        exec <space><a-i>w <a-k>\A\w+\z<ret>
        set-option buffer curword "\b\Q%val{selection}\E\b"
    } catch %{
        set-option buffer curword ''
    } }
}
add-highlighter global/ dynregex '%opt{curword}' 0:CurWord

# Find files under current directory
# ──────────────────────────────────

def find -params 1 -shell-script-candidates %{ find -type f } %{ edit %arg{1} }

# Fuzzy finder
# ────────────

define-command choose-buffers -docstring %{
  Select an open buffer
} %{
  evaluate-commands %sh{
    BUFFER=$(printf "%s\n" "${kak_buflist}" | tr " " "\n" | choose | tr -d \')
    if [ -n "$BUFFER" ]; then
      printf "%s\n" "buffer ${BUFFER}"
    fi
  }
}

define-command choose-files -docstring %{
  Select files in project
} %{
  nop %sh{
    FILE=$(git ls-files --cache | choose)
    if [ -n "$FILE" ]; then
      printf 'eval -client %%{%s} edit %%{%s}\n' "${kak_client}" "${FILE}" | kak -p "${kak_session}"
    fi
  }
}

declare-user-mode fuzzy
map -docstring "Fuzzy finder commands" global user <f> %{:enter-user-mode fuzzy<ret>}
map global fuzzy -docstring "buffers - Select an open buffer" b ': choose-buffers<ret>'
map global fuzzy -docstring "files - Select files in project" f ': choose-files<ret>'

# Linting JavaScript
# ──────────────────

hook global WinSetOption filetype=javascript %{
    set buffer lintcmd 'eslint --config .eslintrc.js -f ~/.fnm/node-versions/v14.9.0/installation/lib/node_modules/eslint-formatter-kakoune/index.js'
    lint-enable
    lint
}

define-command format-eslint -docstring %{
    Formats the current buffer using eslint.
    Respects your local project setup in eslintrc.
} %{
    evaluate-commands -draft -no-hooks -save-regs '|' %{
        # Select all to format
        execute-keys '%'

        # eslint does a fix-dry-run with a json formatter which results in a JSON output to stdout that includes the fixed file.
        # jq then extracts the fixed file output from the JSON. -j returns the raw output without any escaping.
        set-register '|' %{
            format_out="$(mktemp)"
            cat | \
            npx eslint --format json \
                       --fix-dry-run \
                       --stdin \
                       --stdin-filename "$kak_buffile" | \
            jq -j ".[].output" > "$format_out"
            if [ $? -eq 0 ] && [ $(wc -c < "$format_out") -gt 4 ]; then
                cat "$format_out"
            else
                printf 'eval -client %s %%{ fail eslint formatter returned an error %s }\n' "$kak_client" "$?" | kak -p "$kak_session"
                printf "%s" "$kak_quoted_selection"
            fi
            rm -f "$format_out"
        }

        # Replace all with content from register:
        execute-keys '|<ret>'
    }
}

# Plugins
# ───────

source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option global softtabstop 2
} config %{
    # these languages will use `expandtab' behavior
    hook global WinSetOption filetype=(rust|markdown|kak|lisp|scheme|sh|perl) expandtab
    # these languages will use `noexpandtab' behavior
    hook global WinSetOption filetype=(makefile|gas) noexpandtab
    # these languages will use `smarttab' behavior
    hook global WinSetOption filetype=(c|cpp) smarttab
}
plug "Bodhizafa/kak-rainbow" config %{
  hook global WinSetOption filetype=(rust|python|c|c++|scheme|lisp|clojure|typescript|javascript|json) %{
    rainbow-enable-window
  }
}
plug "lePerdu/kakboard" config %{
    hook global WinCreate .* %{ kakboard-enable }
}
plug "ul/kak-lsp" do %{
    cargo install --locked --force --path .
} config %{
    map -docstring "Language server commands" global user <l> %{:enter-user-mode lsp<ret>}

    hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
        lsp-enable-window
        lsp-auto-hover-enable
    }

    # Inlay hints for rust-analyzer
    hook global WinSetOption filetype=rust %{
        hook window -group rust-inlay-hints BufReload .* rust-analyzer-inlay-hints
        hook window -group rust-inlay-hints NormalIdle .* rust-analyzer-inlay-hints
        hook window -group rust-inlay-hints InsertIdle .* rust-analyzer-inlay-hints
        hook -once -always window WinSetOption filetype=.* %{
            remove-hooks window rust-inlay-hints
        }
    }

    # Semantic tokens
    hook global WinSetOption filetype=<language> %{
        hook window -group semantic-tokens BufReload .* lsp-semantic-tokens
        hook window -group semantic-tokens NormalIdle .* lsp-semantic-tokens
        hook window -group semantic-tokens InsertIdle .* lsp-semantic-tokens
        hook -once -always window WinSetOption filetype=.* %{
            remove-hooks window semantic-tokens
        }
    }

    eval %sh{kak-lsp --kakoune -s $kak_session}
}
plug "https://gitlab.com/Screwtapello/kakoune-cargo" config %{
    map -docstring "Cargo commands" global user <c> %{:enter-user-mode cargo<ret>}
}

# Mappings
# ────────

map global normal <%> '<c-s>%' # Save position before %
map global normal '#' :comment-line<ret>

# Enable <tab>/<s-tab> for insert completion selection
# ────────────────────────────────────────────────────

hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <s-tab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <s-tab> <c-p> }
