#!/bin/sh

# clj - Clojure launcher script

BREAK_CHARS="\(\){}[],^%$#@\"\";:''|\\"

cljjar="/usr/local/Cellar/clojure/1.3.0/clojure-1.3.0.jar"
cljclass='clojure.main'
cljcompletions="$HOME/.clj_completions"

CP=$CLASSPATH:${cljjar}
CP=$CP:"/Users/gianni/Projects/clojure/clojure-contrib-1.3.0-SNAPSHOT.jar"
CP=$CP:${PWD}

# Add extra jars as specified by `.clojure` file
# Borrowed from <http://github.com/mreid/clojure-framework>
if [ -f .clojure ]; then
  CP=$CP:`cat .clojure`
fi

if [ $# -eq 0 ]; then
  rlwrap --remember -c -b $BREAK_CHARS -f $cljcompletions java -cp $CP $cljclass
else
  exec java -classpath $CP $cljclass $*
fi

